version: "3"

services:
  redis:
    container_name: opengpts-redis
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis-volume:/data
  backend:
    container_name: opengpts-backend
    build:
      context: .
    ports:
      - "8100:8000" # Backend is accessible on localhost:8100 and serves the frontend
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    environment:
      REDIS_URL: "redis://opengpts-redis:6379"
    command:
      - --reload
