version: '3'

services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redis
    ports:
      - "6379:6379"  # Redis is accessible on localhost:6379

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8100:8100"  # Backend is accessible on localhost:8100
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      PORT: 8100
      REDIS_URL: "redis://redis:6379"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"  # Frontend is accessible on localhost:5173
    environment:
      VITE_BACKEND_URL: "http://backend:8100"
