version: '3'

services:
  redis:
    image: redislabs/redisearch:latest
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
  backend:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: backend/Dockerfile  # Specify the custom Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - redis
    env_file:
      - .env  # Use the .env file to load environment variables
    environment:
      PORT: 8100
      REDIS_URL: "redis://redis:6379"
  frontend:
    build:
      context: .  # Use the current directory as the build context
      dockerfile: frontend/Dockerfile  # Specify the custom Dockerfile
    ports:
      - "5173:5173"
