version: "3"

services:
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./postgres-volume:/var/lib/postgresql/data
  backend:
    container_name: opengpts-backend
    build:
      context: backend
    ports:
      - "8100:8000" # Backend is accessible on localhost:8100
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./backend:/backend
    environment:
      POSTGRES_HOST: "postgres"
    command:
      - --reload
  frontend:
    container_name: opengpts-frontend
    build:
      context: frontend
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "5173:5173" # Frontend is accessible on localhost:5173
    environment:
      VITE_BACKEND_URL: "http://opengpts-backend:8000"
